name: Create OSP Linux images
on: 
#  release:
#    types: [published]
  push

jobs:
  build:
    strategy:
        matrix:
            r_version: [3.6.3] #[3.6.3, 4.1.0]
            os_version: [centos7, bionic]
    runs-on: ubuntu-latest
    steps:
      - name: tag name
        id: tag_name
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF##*/}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/workflows/Dockerfile
          build-args: |
            r_version=${{ matrix.r_version }}
            os_version=${{ matrix.os_version }}
          push: true
          tags: |
            ghcr.io/yuri05/base-r${{ matrix.r_version }}-${{ matrix.os_version }}:${{ steps.tag_name.outputs.SOURCE_TAG}}
#            ghcr.io/yuri05/base-r${{ matrix.r_version }}-${{ matrix.os_version }}:latest
#            docker.pkg.github.com/yuri05/hello-github-actions/base-r${{ matrix.r_version }}-${{ matrix.os_version }}:${{ steps.tag_name.outputs.SOURCE_TAG}}
